# Generated by Django 5.0.14 on 2025-04-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('colegio', models.CharField(max_length=100)),
                ('grupo', models.CharField(blank=True, choices=[('sweet', 'Sweet'), ('smart', 'Smart'), ('teens', 'Teens'), ('otro', 'Otro')], max_length=20, null=True)),
                ('dias', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('modalidad', models.CharField(max_length=50)),
                ('medio_referencia', models.CharField(max_length=100)),
                ('motivo_estudio', models.CharField(blank=True, choices=[('academico', 'Académico'), ('viaje', 'Viaje'), ('laboral', 'Laboral')], max_length=20, null=True)),
                ('archivo_formulario', models.FileField(blank=True, null=True, upload_to='formularios/')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_estudiante', models.CharField(blank=True, choices=[('normal', 'Normal'), ('profesional', 'Profesional'), ('independiente', 'Independiente')], max_length=20, null=True)),
                ('celular_referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estudios_ingles_previos', models.TextField(blank=True, null=True)),
                ('institucion_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_inscripcion', models.CharField(choices=[('anual', 'Anual'), ('vacacional', 'Vacacional'), ('particular', 'Clases particulares'), ('becado', 'Becado')], default='anual', max_length=20)),
                ('forma_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('clases_particulares', models.BooleanField(default=False)),
                ('material_entregado', models.BooleanField(default=False)),
                ('firmado', models.BooleanField(default=False)),
                ('recibido', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
    ]
