# Generated by Django 5.2.1 on 2025-05-26 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_acumulada', models.IntegerField()),
                ('primer_examen', models.IntegerField()),
                ('segundo_examen', models.IntegerField()),
                ('examen_final', models.IntegerField()),
            ],
            options={
                'db_table': 'nota',
            },
        ),
        migrations.CreateModel(
            name='TestVak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual', models.FloatField()),
                ('auditorio', models.FloatField()),
                ('lectutura', models.FloatField()),
                ('kinestesico', models.FloatField()),
                ('estilo_predominante', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'test_vak',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_participate', models.SmallIntegerField()),
                ('is_tarea', models.SmallIntegerField()),
                ('is_present', models.BooleanField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
        ),
    ]
