# Generated by Django 5.2.1 on 2025-06-22 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciondiaria',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
