# Generated by Django 5.0.14 on 2025-04-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('directivos', '0001_initial'),
        ('estudiantes', '0001_initial'),
        ('secretarias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.CASCADE, to='asignaturas.asignatura')),
                ('id_directivo', models.ForeignKey(db_column='id_directivo', on_delete=django.db.models.deletion.CASCADE, to='directivos.directivo')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('id_secretaria', models.ForeignKey(db_column='id_secretaria', on_delete=django.db.models.deletion.CASCADE, to='secretarias.secretaria')),
            ],
            options={
                'db_table': 'inscripcion',
            },
        ),
    ]
