# Generated by Django 5.2.1 on 2025-05-26 00:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Nombre de usuario único', max_length=150, unique=True)),
                ('carnet', models.CharField(default='SIN_CARNET', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('direccion', models.TextField(default='Dirección por defecto')),
                ('telefono', models.CharField(default='0000000000', max_length=15)),
                ('fecha_nacimiento', models.DateField(default=django.utils.timezone.now)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('hijo', models.JSONField(blank=True, default=dict, null=True)),
                ('domicilio', models.CharField(default='Domicilio por defecto', max_length=255)),
                ('rol', models.CharField(default='Rol por defecto', max_length=100)),
                ('ocupacion', models.TextField(blank=True, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
