# Generated by Django 5.2.1 on 2025-06-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='hijo',
            new_name='tutor',
        ),
    ]
