# Generated by Django 5.2.1 on 2025-05-25 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='Apellidos por defecto', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='carnet',
            field=models.CharField(default='SIN_CARNET', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(default='Dirección por defecto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(default='Domicilio por defecto', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='hijo',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='Nombre por defecto', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ocupacion',
            field=models.TextField(blank=True, default='Ocupación por defecto', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='parentesco',
            field=models.CharField(blank=True, default='Parentesco por defecto', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Rol por defecto', max_length=100),
        ),
    ]
