# Generated by Django 5.0.14 on 2025-04-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_trabajo', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario', models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='TieneTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.CASCADE, to='tutores.tutor')),
            ],
            options={
                'db_table': 'tiene_tutor',
                'unique_together': {('estudiante', 'tutor')},
            },
        ),
    ]
