# Generated by Django 5.0.14 on 2025-04-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_contrato', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.CASCADE, to='asignaturas.asignatura')),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='docentes.docente')),
            ],
            options={
                'db_table': 'docente_asignatura',
                'unique_together': {('docente', 'asignatura')},
            },
        ),
    ]
