# Generated by Django 5.0.14 on 2025-04-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarkResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prueba', models.DateField()),
                ('visual', models.FloatField()),
                ('auditivo', models.FloatField()),
                ('lectura', models.FloatField()),
                ('kinestesico', models.FloatField()),
                ('estilo_predominante', models.CharField(max_length=50)),
                ('id_estudiante', models.OneToOneField(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'vark_resultado',
            },
        ),
    ]
