# Generated by Django 5.0.14 on 2025-04-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial1', models.FloatField()),
                ('parcial2', models.FloatField()),
                ('examen_final', models.FloatField()),
                ('promedio', models.FloatField()),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='docentes.docente')),
                ('id_inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='inscripciones.inscripcion')),
            ],
            options={
                'db_table': 'nota',
            },
        ),
    ]
